openapi: 3.0.0
info:
  title: Todo app
  description: Todo app is an application that helps users manage their time by reminding them of their items they have planned to achieve over a given period.

version: 0.1.9

servers:
  - url: /api
    description: Todo app base address

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
          example: test
        lastName:
          type: string
          example: test
        email:
          type: string
          example: test@test.com
        password:
          type: string
          example: test12

paths:
  /users/signup:
    post:
      summary: Create a new user account.
      description: Creates user account.
      tags:
        - User
      requestBody:
        description: Input fields required to add new account
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/User'
      responses:
        201:
          description: User account created
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                    example: test
                  lastName:
                    type: string
                    example: test
                  email:
                    type: string
                    example: test@test.com
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        400:
          description: Error in input fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: firstName is required
        409:
          description: An account exists with similar details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An account with similar email address exists
  /users/login:
    post:
      summary: Endpoint for user to log in
      description: Endpoint for user to log in
      tags:
        - User
      requestBody:
        description: Input fields required to add new account
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@test.com
                password:
                  type: string
                  example: test12
      responses:
        200:
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                    example: test
                  lastName:
                    type: string
                    example: test
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        401:
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Wrong email or password
  /projects:
    post:
      summary: Endpoint for creating a new project
      description: A user creates a project using this endpoint
      tags:
        - Projects
      security:
        - {}
        - bearerAuth: []
      requestBody:
        description: Input fields required for creating new project
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: To buy a car
                description:
                  type: string
                  example: For taxi
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  title:
                    type: string
                    example: Buy a car
                  description:
                    type: string
                    example: for taxi
        409:
          description: Conflict in project title
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Another project with similar title exists
    get:
      summary: Retrieve all projects for current logged in user
      tags:
        - Projects
      security:
        - {}
        - bearerAuth: []
      responses:
        200:
          description: Retrieved all projects for the logged in user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    title:
                      type: string
                      example: Buy car
                    description:
                      type: string
                      example: for taxi
